#############################################
######### Continuous Integration .. #########
#############################################
  
sudo: required
services: 
  - docker 

language: java
jdk:
  - openjdk8

before_install:
  - chmod +x mvnw

script: ./mvnw clean install


jobs:
  include:
    - stage: test
      script: ./mvnw clean test

############################################
######### Continuous Deployment .. #########
############################################

before_deploy: 
  - docker build -t dockertunis/hospital-management-springboot -f Dockerfile .

deploy:
  provider: heroku
  api_key:
    secure: "$HEROKU_API_KEY"
  app: "$HEROKU_APP_NAME"
  on:
    branch: master