###################################################
###   Continuous Integration with JAVA ENV ...  ###
###################################################

# language: java
# jdk:
#   - openjdk8

# before_install:
#   - chmod +x mvnw

# script: ./mvnw clean install


# jobs:
#   include:
#     - stage: Test
#       script: ./mvnw clean test



###########################################################
###   Continuous Integration with Docker Container ...  ###
###########################################################

sudo: required
services: 
  - docker 

before_install: 
  - docker build -t dockertunis/hospital-management-springboot -f Dockerfile .

script: 
  - docker run dockertunis/hospital-management-springboot ./mvnw clean test
